#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

if [ -f ~/.bash_aliases ]; then
. ~/.bash_aliases
fi

export PATH="$HOME/Code/Scripts:$PATH"
export EDITOR=vim
export VISUAL=vim
cp "$HOME/.bashrc" "$HOME/Code/Scripts/bashrc"